### ISSUE TITLE
add a file in the created directory

### ISSUE THREAD

**Issue by ekanath25** [ipfs/interface-ipfs-core#371] opened 2018-09-21 18:51 UTC
I am creating a IPFS directory using mkdir command, i want to add a file in the created directory using hash of that directory.

Please help me Thanks in advance.

**Comment by alanshaw** [comment] 2018-12-04 14:18
duplicate of https://github.com/ipfs/js-ipfs-http-client/issues/861

**Closed by alanshaw** 2018-12-04 14:18 UTC
